title: shadetree engineering
email: aholmes@omnom.net
description: >-
  i'm not a software developer, i just play one on TV
baseurl: ""
url: "https://neggles.github.io"

twitter_username: sirneggles
github_username:  neggles
instagram_username: sirneggles

show_excerpts: true
header_pages:
  - electronics.md
  - software.md
  - hackery.md
  - repos.md

repository: neggles/neggles.github.io
github:
  is_project_page: false
  is_user_page: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-remote-theme

# Plugin settings
remote_theme: jekyll/minima
minima:
  skin: dark

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
